POST http://localhost:3000/posts
Content-Type: application/json

{
    "itemName": "Carteira de Couro",
    "itemDesc": "Carteira de couro preta com documentos e cartões de crédito.",
    "itemLoc": "Shopping Royal Plaza",
    "itemDate": "2025-09-10",
    "posterName": "Carlos Silva",
    "stat": "Perdido"
}

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "itemName": "Chave de Carro",
    "itemDesc": "Chave de carro com chaveiro azul e logotipo da Toyota.",
    "itemLoc": "Estacionamento do Supermercado Big",
    "itemDate": "2025-09-12",
    "posterName": "Ana Paula",
    "stat": "Encontrado"
}

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "itemName": "Óculos de Sol",
    "itemDesc": "Óculos de sol Ray-Ban com armação dourada e lentes escuras.",
    "itemLoc": "Praça Saldanha Marinho",
    "itemDate": "2025-09-14",
    "posterName": "Marcos Oliveira",
    "stat": "Perdido"
}

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "itemName": "Relógio de Pulso",
    "itemDesc": "Relógio de pulso prateado da marca Casio.",
    "itemLoc": "Academia FitLife",
    "itemDate": "2025-09-16",
    "posterName": "Fernanda Costa",
    "stat": "Encontrado"
}

###
